### ISSUE TITLE
krb525d on debian buster

### ISSUE THREAD

**Issue by vchlum** [CESNET/krb525#3]
I am not able to successfully use krb525d on the Debian buster even if patch #2 is applied.

The server is started:
```
/usr/lib/heimdal-servers/krb525d krb525d -c /etc/heimdal-kdc/krb525d.conf -C /etc/heimdal-kdc/kdc.conf -p 13333
```

...but the client returns an error...

```
krb525 -p 13333 -v -C test@PBSPRO
Initializing Kerberos
Ticket to convert is host/heimdal-kdc-d10@PBSPRO for krbtgt/PBSPRO@PBSPRO
Target ticket is test@PBSPRO for krbtgt/PBSPRO@PBSPRO
Could not convert ticket: Failed to convert credentials with heimdal-kdc-d10 (Server error
 from server
)
```
...and syslog shows:
```
Oct 21 13:00:15 heimdal-kdc-d10 krb525d[23201]: Connection: host/heimdal-kdc-d10@PBSPRO from 192.168.1.5
Oct 21 13:00:15 heimdal-kdc-d10 krb525d[23201]: Error -1765328353 get service key for krbtgt/PBSPRO@PBSPRO from db: error Unknown code krb5 31 fetching principal
```
The source of the error is line: 
`h_db.c:114: ret = db->hdb_fetch_kvno(context, db, princ, HDB_F_DECRYPT, 0, entry);`

I am not sure if this an actual error or just misconfiguration. The used configuration is based on the working Debian 9 configuration.

**Comment by kouril** [comment]
Configuration problem, addressed out-of-band.
